# -*- mode: Dockerfile -*-

# This Dockerfile may be used to create an Ubuntu 22.04 image, configured for Swift development.
# From this file's home directory, run: docker build -t swift-build:latest .

FROM --platform=linux/x86_64 swift:focal

USER root
ARG arch

RUN apt update && apt install -y emacs build-essential devscripts debhelper dh-make dpkg-dev
RUN mkdir /root/telemetry

COPY libpl_1.0-1_x86_64.deb /root/telemetry

# This --force-architecture flag is need here because, of course, MacOS uses a different
# virtualization method with docker containers.

RUN dpkg --install --force-architecture /root/telemetry/libpl_1.0-1_x86_64.deb
